### ISSUE TITLE
Changelog for Releases

### ISSUE THREAD

**Issue by majora2007** [TylerBrinks/ExCSS#140]
Multiple versions are released on Nuget, but there doesn't seem to be any notes around what exactly changes between releases. 

Is this something that can be done, either via Github Releases or just a simple Changelog.md file? 

This helps me understand when I should upgrade and what to expect between versions.

**Comment by TylerBrinks** [comment]
That's a reasonable request.  Most of what's been released recently are minor bug fixes documented here in GitHub, but a change log seems reasonable.  If you are familiar with a way to automate it, please hit me up so we can do it sooner than later.

**Comment by majora2007** [comment]
I personally think it's easiest to just maintain a Changelog.md and have each commit go into an unreleased section, so:

```
# Unrealeased:
- Did this, did that

# v0.0.1
- Whatever went into that release
```

This has the benefit that you don't need to maintain much except when you release a new version, you need to update the Changelog and change Unreleased -> the version. The downside to this system is merge conflicts, but the project is pretty mature, so there aren't many PRs being merged, so I don't think that is a major concern. 

I'm sure you could do it via automation, but I'm unfamiliar with your CI/CD pipeline.

**Comment by gdeswardt** [comment]
This can be completely automated using GitHub Workflows and Actions. The changelog will be based on all the pull requests that were merged into the master since the previous release.

A semantic versioning can be automatically calculated using GitVersion from the `git` commit history and produce a value in the format of `{MAJOR}.{MINOR}.{PATCH}`. This will require a tag to be created on the commit for the `4.1.4` release 

```bash
git tag v4.1.4 4e0d475
git push origin v4.1.4
```
A branching strategy would be required to support the automation and propose to use a very simple strategy with small feature branches `feature/{feature-name}` of the master, which is merged back in using pull requests. Once ready to create a release, a release branch is created in the format of `release/v{MAJOR}.{MINOR}.{PATCH}`.

The pre-release version can be published to the NuGet feed as well, with deployment branch controls that require a user/group to approve a release before publishing the release version of the package to NuGet. The NuGet API key can be securely stored in the GitHub repository secrets.

**Comment by gdeswardt** [comment]
I have created a historic tag and release for v4.1.4 which was released last year. The new automated pipelines are now correctly and automatically calculating the semantic version from the git commit history using GitVersion.

**Comment by gdeswardt** [comment]
This has now been automated and verified with version 4.2.0

https://github.com/TylerBrinks/ExCSS/releases/tag/v4.2.0

Closing this issues

**Comment by TylerBrinks** [comment]
@gdeswardt Many thanks for all the help with the CI/CD setup.  Absolutely fantastic work!
